apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80