apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryosg7304.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-service:8080
          - name: TRIPS_API_ENDPOINT
            value: http://trips-service:8080
          - name: BING_MAPS_KEY
            value: Ajkq4SssTht6F09orSoNKNLgYLvI_6alCzw7_Rcdztr_scDpRS2OdjMhLougy_m5