apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80