apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: web
spec:
  type: ExternalName
  externalName: user-java-service.api.svc.cluster.local
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080