kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-reader-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-reader-access
subjects:
- kind: Group
  namespace: api
  name: 79fa7d92-dcfa-4ce8-8b2c-5c23bc56b798